name: Simple Proxy

on:
  workflow_dispatch:

jobs:
  proxy:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Setup Proxy
      run: |
        sudo apt update
        sudo apt install -y squid
        echo "http_port 3128" | sudo tee /etc/squid/squid.conf
        echo "http_access allow all" | sudo tee -a /etc/squid/squid.conf
        sudo systemctl restart squid
        
    - name: Show IP
      run: curl ifconfig.me
        
    - name: Keep Running
      run: sleep 6h
